"""
SemanticLayer domain — Pydantic v2 schemas.

Defines request and response schemas for table and column annotations (business descriptions).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


class AnnotationCreate(BaseModel):
    """Request payload for creating a schema annotation."""

    target_type: Literal["table", "column"] = Field(
        ..., description="Target entity type: 'table' or 'column'"
    )
    schema_table_id: uuid.UUID | None = Field(
        default=None, description="ID of the schema table when target_type is 'table'"
    )
    schema_column_id: uuid.UUID | None = Field(
        default=None, description="ID of the schema column when target_type is 'column'"
    )
    note: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Business description or context for the table or column",
    )
    is_auto_generated: bool = Field(
        default=False,
        description="Whether this annotation was auto-generated by LLM",
    )

    @model_validator(mode="after")
    def validate_target_id(self) -> AnnotationCreate:
        """Validate that exactly one target ID is provided corresponding to target_type."""
        if self.target_type == "table":
            if not self.schema_table_id or self.schema_column_id is not None:
                raise ValueError(
                    "When target_type is 'table', 'schema_table_id' must be provided and 'schema_column_id' must be None."
                )
        elif self.target_type == "column":
            if not self.schema_column_id or self.schema_table_id is not None:
                raise ValueError(
                    "When target_type is 'column', 'schema_column_id' must be provided and 'schema_table_id' must be None."
                )
        return self


class AnnotationUpdate(BaseModel):
    """Request payload for updating an existing schema annotation."""

    note: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Updated business description or context",
    )


class AnnotationResponse(BaseModel):
    """Response payload representing a schema annotation."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    project_id: uuid.UUID
    connection_id: uuid.UUID
    schema_table_id: uuid.UUID | None = None
    schema_column_id: uuid.UUID | None = None
    target_type: str
    note: str
    is_auto_generated: bool = False
    created_at: datetime
    updated_at: datetime
